#!/usr/bin/env python3
"""Generated by gen_encoder.py from rules.json — phenotype: Fruit intake (kg_version 1782339456).
Applies the encoding rules to a UK Biobank extract. Fail-loud on absent fields (--lenient to emit NaN). Usage: python3 encode.py <extract.csv> [-o out.csv] [--id-col eid] [--lenient]"""

import argparse
import json
import re
import sys

import numpy as np
import pandas as pd


def _cols(df, fid):
    """All extract columns for a field: classic {fid}-{i}.{a}, RAP p{fid}_i{i}_a{a}, or bare {fid}."""
    pats = (re.compile(rf"^{fid}-\d+\.\d+$"), re.compile(rf"^p{fid}_i\d+(_a\d+)?$"))
    return [c for c in df.columns if str(c) == str(fid) or any(p.match(str(c)) for p in pats)]


def _agg(sub, how):
    if how == "mean":
        return sub.mean(axis=1)
    if how == "max":
        return sub.max(axis=1)
    if how == "min":
        return sub.min(axis=1)
    if how == "sum":
        return sub.sum(axis=1, min_count=1)
    if how == "first_non_null":
        return sub.bfill(axis=1).iloc[:, 0]
    raise ValueError(f"unknown instance_agg {how!r}")


def _combine(parts, how):
    m = pd.concat(parts, axis=1)
    if how == "sum":
        return m.sum(axis=1, min_count=1)
    if how == "max":
        return m.max(axis=1)
    if how == "min":
        return m.min(axis=1)
    if how == "mean":
        return m.mean(axis=1)
    if how in ("priority", "first_non_null"):
        out = m.iloc[:, 0].copy()
        for i in range(1, m.shape[1]):
            out = out.fillna(m.iloc[:, i])
        return out
    raise ValueError(f"unknown combine {how!r}")


def _score(v, sc):
    op = sc["op"]
    if op == "in":
        m = v.isin(sc["values"])
    else:
        t = sc["threshold"]
        m = {">=": v >= t, "<=": v <= t, ">": v > t, "<": v < t, "==": v == t}[op]
    out = pd.Series(np.where(m, sc.get("true", 1), sc.get("false", 0)), index=v.index, dtype="float64")
    out[v.isna()] = np.nan  # never invent a label for a missing input
    return out


def encode_variable(df, spec, strict):
    parts = []
    for f in spec["fields"]:
        fid = f["field_id"]
        cols = _cols(df, fid)
        if not cols:
            msg = f"field {fid} ({spec['name']}) not in extract — no columns match {fid}-<instance>.<array>"
            if strict:
                sys.exit(f"FAIL: {msg}")
            sys.stderr.write(f"WARN: {msg}; emitting NaN\n")
            parts.append(pd.Series(np.nan, index=df.index))
            continue
        sub = df[cols].apply(pd.to_numeric, errors="coerce")
        mc = f.get("missing_codes") or []
        if mc:
            sub = sub.mask(sub.isin(mc))
        rec = f.get("recode") or {}
        if rec:
            sub = sub.replace({float(k): v for k, v in rec.items()})
        parts.append(_agg(sub, f.get("instance_agg", "mean")))
    v = _combine(parts, spec.get("combine", "first_non_null"))
    if spec.get("score"):
        v = _score(v, spec["score"])
    return v


def main():
    ap = argparse.ArgumentParser(description=f"Encode phenotype: {RULES.get('phenotype','')}")
    ap.add_argument("extract", help="UKB extract CSV (wide: eid + {field}-{instance}.{array} columns)")
    ap.add_argument("-o", "--out", default="phenotype.csv")
    ap.add_argument("--id-col", default="eid")
    ap.add_argument("--lenient", action="store_true",
                    help="emit NaN + warn for absent fields instead of failing")
    a = ap.parse_args()
    df = pd.read_csv(a.extract)
    if a.id_col not in df.columns:
        sys.exit(f"FAIL: id column {a.id_col!r} not in extract; columns start with {list(df.columns)[:5]}")
    out = pd.DataFrame({a.id_col: df[a.id_col]})
    for spec in RULES["variables"]:
        out[spec["name"]] = encode_variable(df, spec, strict=not a.lenient).values
    out.to_csv(a.out, index=False)
    sys.stderr.write(f"OK  wrote {a.out}  rows={len(out)}  "
                     f"variables={[s['name'] for s in RULES['variables']]}\n")

RULES = json.loads(r'''
{
  "phenotype": "Fruit intake",
  "kg_version": "1782339456",
  "source_concept": "known_composite; whole fruit (touchscreen, pieces/day) vs 24h-recall (grams) — unit-incompatible, given as two variables",
  "variables": [
    {
      "name": "fresh_fruit_pieces_per_day",
      "description": "Habitual whole fruit (touchscreen), pieces/day",
      "fields": [
        {
          "field_id": 1309,
          "title": "Fresh fruit intake",
          "missing_codes": [
            -1,
            -3
          ],
          "recode": {
            "-10": 0.5
          },
          "instance_agg": "mean",
          "role": "primary"
        },
        {
          "field_id": 1319,
          "title": "Dried fruit intake",
          "missing_codes": [
            -1,
            -3
          ],
          "recode": {
            "-10": 0.5
          },
          "instance_agg": "mean",
          "role": "primary"
        }
      ],
      "combine": "sum",
      "score": null,
      "rationale": "Fresh + dried pieces/day. -1/-3 -> NaN; -10 'Less than one' -> 0.5; mean across instances 0-3, then sum."
    },
    {
      "name": "fruit_grams_per_day_24h",
      "description": "Total whole-fruit grams from 24h-recall food groups",
      "fields": [
        {
          "field_id": 26089,
          "title": "Apples and pears",
          "instance_agg": "mean",
          "role": "component"
        },
        {
          "field_id": 26090,
          "title": "Berries",
          "instance_agg": "mean",
          "role": "component"
        },
        {
          "field_id": 26091,
          "title": "Citrus",
          "instance_agg": "mean",
          "role": "component"
        },
        {
          "field_id": 26092,
          "title": "Dried fruit",
          "instance_agg": "mean",
          "role": "component"
        },
        {
          "field_id": 26093,
          "title": "Other fruit",
          "instance_agg": "mean",
          "role": "component"
        },
        {
          "field_id": 26094,
          "title": "Stewed fruit",
          "instance_agg": "mean",
          "role": "component"
        }
      ],
      "combine": "sum",
      "score": null,
      "rationale": "Sum of fruit food-group grams; mean across 24h-recall instances; encoding 0 (no special codes); juice 26095 excluded by scope."
    }
  ],
  "dropped": [
    {
      "field_id": 104340,
      "title": "Fresh tomato intake",
      "reason": "botanical fruit but dietary vegetable"
    },
    {
      "field_id": 26143,
      "title": "Tomatoes",
      "reason": "dietary vegetable, not fruit"
    },
    {
      "field_id": 26146,
      "title": "Other vegetables, including mushrooms, fruiting and mixed vegetables",
      "reason": "'fruiting' = botanical, not dietary fruit"
    },
    {
      "field_id": 26095,
      "title": "Fruit juice",
      "reason": "scope: 100% juice analyzed separately from whole fruit"
    }
  ]
}
''')

if __name__ == "__main__":
    main()
