#!/usr/bin/env python3
"""Generated by gen_encoder.py from rules.json — phenotype: GAD-7 (kg_version 1782339456).
Applies the encoding rules to a UK Biobank extract. Fail-loud on absent fields (--lenient to emit NaN). Usage: python3 encode.py <extract.csv> [-o out.csv] [--id-col eid] [--lenient]"""

import argparse
import json
import re
import sys

import numpy as np
import pandas as pd


def _cols(df, fid):
    """All extract columns for a field: classic {fid}-{i}.{a}, RAP p{fid}_i{i}_a{a}, or bare {fid}."""
    pats = (re.compile(rf"^{fid}-\d+\.\d+$"), re.compile(rf"^p{fid}_i\d+(_a\d+)?$"))
    return [c for c in df.columns if str(c) == str(fid) or any(p.match(str(c)) for p in pats)]


def _agg(sub, how):
    if how == "mean":
        return sub.mean(axis=1)
    if how == "max":
        return sub.max(axis=1)
    if how == "min":
        return sub.min(axis=1)
    if how == "sum":
        return sub.sum(axis=1, min_count=1)
    if how == "first_non_null":
        return sub.bfill(axis=1).iloc[:, 0]
    raise ValueError(f"unknown instance_agg {how!r}")


def _combine(parts, how):
    m = pd.concat(parts, axis=1)
    if how == "sum":
        return m.sum(axis=1, min_count=1)
    if how == "max":
        return m.max(axis=1)
    if how == "min":
        return m.min(axis=1)
    if how == "mean":
        return m.mean(axis=1)
    if how in ("priority", "first_non_null"):
        out = m.iloc[:, 0].copy()
        for i in range(1, m.shape[1]):
            out = out.fillna(m.iloc[:, i])
        return out
    raise ValueError(f"unknown combine {how!r}")


def _score(v, sc):
    op = sc["op"]
    if op == "in":
        m = v.isin(sc["values"])
    else:
        t = sc["threshold"]
        m = {">=": v >= t, "<=": v <= t, ">": v > t, "<": v < t, "==": v == t}[op]
    out = pd.Series(np.where(m, sc.get("true", 1), sc.get("false", 0)), index=v.index, dtype="float64")
    out[v.isna()] = np.nan  # never invent a label for a missing input
    return out


def encode_variable(df, spec, strict, computed):
    parts = []
    for f in spec["fields"]:
        if "variable" in f:  # reference an already-computed output variable (e.g. a sum of item scores)
            ref = f["variable"]
            if ref not in computed:
                sys.exit(f"FAIL: {spec['name']} references variable {ref!r} before it is computed "
                         f"(define it earlier in 'variables')")
            parts.append(computed[ref])
            continue
        fid = f["field_id"]
        cols = _cols(df, fid)
        if not cols:
            msg = f"field {fid} ({spec['name']}) not in extract — no columns match {fid}-<instance>.<array>"
            if strict:
                sys.exit(f"FAIL: {msg}")
            sys.stderr.write(f"WARN: {msg}; emitting NaN\n")
            parts.append(pd.Series(np.nan, index=df.index))
            continue
        sub = df[cols].apply(pd.to_numeric, errors="coerce")
        mc = f.get("missing_codes") or []
        if mc:
            sub = sub.mask(sub.isin(mc))
        rec = f.get("recode") or {}
        if rec:
            sub = sub.replace({float(k): v for k, v in rec.items()})
        parts.append(_agg(sub, f.get("instance_agg", "mean")))
    v = _combine(parts, spec.get("combine", "first_non_null"))
    if spec.get("score"):
        v = _score(v, spec["score"])
    return v


def main():
    ap = argparse.ArgumentParser(description=f"Encode phenotype: {RULES.get('phenotype','')}")
    ap.add_argument("extract", help="UKB extract CSV (wide: eid + {field}-{instance}.{array} columns)")
    ap.add_argument("-o", "--out", default="phenotype.csv")
    ap.add_argument("--id-col", default="eid")
    ap.add_argument("--lenient", action="store_true",
                    help="emit NaN + warn for absent fields instead of failing")
    a = ap.parse_args()
    df = pd.read_csv(a.extract)
    if a.id_col not in df.columns:
        sys.exit(f"FAIL: id column {a.id_col!r} not in extract; columns start with {list(df.columns)[:5]}")
    out = pd.DataFrame({a.id_col: df[a.id_col]})
    computed = {}
    for spec in RULES["variables"]:
        s = encode_variable(df, spec, strict=not a.lenient, computed=computed)
        out[spec["name"]] = s.values
        computed[spec["name"]] = s
    out.to_csv(a.out, index=False)
    sys.stderr.write(f"OK  wrote {a.out}  rows={len(out)}  "
                     f"variables={[s['name'] for s in RULES['variables']]}\n")

RULES = json.loads(r'''
{
  "phenotype": "GAD-7",
  "kg_version": "1782339456",
  "source_concept": "validated_instrument (Spitzer 2006); 7 items harmonized to 0-3 then summed",
  "variables": [
    {
      "name": "gad7_item1",
      "description": "GAD-7 item 1: Feeling nervous, anxious, or on edge (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20506,
          "title": "Recent feelings or nervousness or anxiety",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29058,
          "title": "Recent feelings or nervousness or anxiety",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item2",
      "description": "GAD-7 item 2: Not being able to stop or control worrying (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20509,
          "title": "Recent inability to stop or control worrying",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29059,
          "title": "Recent inability to stop or control worrying",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item3",
      "description": "GAD-7 item 3: Worrying too much about different things (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20520,
          "title": "Recent worrying too much about different things",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29060,
          "title": "Recent worrying too much about different things",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item4",
      "description": "GAD-7 item 4: Trouble relaxing (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20515,
          "title": "Recent trouble relaxing",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29061,
          "title": "Recent trouble relaxing",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item5",
      "description": "GAD-7 item 5: Being so restless that it is hard to sit still (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20516,
          "title": "Recent restlessness",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29062,
          "title": "Recent restlessness",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item6",
      "description": "GAD-7 item 6: Becoming easily annoyed or irritable (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20505,
          "title": "Recent easy annoyance or irritability",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29063,
          "title": "Recent easy annoyance or irritability",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_item7",
      "description": "GAD-7 item 7: Feeling afraid as if something awful might happen (0-3, last 2 weeks)",
      "fields": [
        {
          "field_id": 20512,
          "title": "Recent feelings of foreboding",
          "recode": {
            "1": 0,
            "2": 1,
            "3": 2,
            "4": 3
          },
          "missing_codes": [
            -818
          ],
          "instance_agg": "max",
          "role": "primary (MHQ, 1-4 -> 0-3)"
        },
        {
          "field_id": 29064,
          "title": "Recent feelings of foreboding",
          "missing_codes": [
            -3
          ],
          "instance_agg": "max",
          "role": "equivalent (online, 0-3)"
        }
      ],
      "combine": "max",
      "score": null,
      "rationale": "Harmonize MHQ (enc 504, 1-4) and online (enc 168, 0-3) each to 0-3; take max across the equivalent items (highest available report)."
    },
    {
      "name": "gad7_total",
      "description": "GAD-7 total score (sum of the 7 items, range 0-21)",
      "fields": [
        {
          "variable": "gad7_item1"
        },
        {
          "variable": "gad7_item2"
        },
        {
          "variable": "gad7_item3"
        },
        {
          "variable": "gad7_item4"
        },
        {
          "variable": "gad7_item5"
        },
        {
          "variable": "gad7_item6"
        },
        {
          "variable": "gad7_item7"
        }
      ],
      "combine": "sum",
      "score": null,
      "rationale": "Sum of the seven 0-3 item scores. A missing item is skipped (min_count=1)."
    },
    {
      "name": "gad7_moderate_or_worse",
      "description": "GAD-7 >= 10 (moderate or worse anxiety)",
      "fields": [
        {
          "variable": "gad7_total"
        }
      ],
      "combine": "first_non_null",
      "score": {
        "op": ">=",
        "threshold": 10,
        "true": 1,
        "false": 0
      },
      "rationale": "Standard GAD-7 cutoff: total >= 10 indicates clinically significant anxiety (Spitzer 2006)."
    }
  ],
  "dropped": [
    {
      "field_id": 1970,
      "title": "Nervous feelings",
      "reason": "lifetime trait (touchscreen), not 2-week frequency; last-resort fallback only"
    },
    {
      "field_id": 2070,
      "title": "Frequency of tenseness / restlessness in last 2 weeks",
      "reason": "related symptom, not the exact GAD-7 item; lower priority"
    },
    {
      "field_id": 23045,
      "title": "Very nervous mood over last week",
      "reason": "different timeframe (last week) and scale; excluded for harmonization"
    }
  ]
}
''')

if __name__ == "__main__":
    main()
